### ISSUE TITLE
Premature drop w/ JanetAbstract

### ISSUE THREAD

**Issue by yrns** [GrayJack/janetrs#6]
I've noticed that for non-`Copy` types, the passed value to `JanetAbstract::new` gets dropped immediately when the mutable pointer it gets moved into goes out of scope. This isn't ideal obviously, so I've been wrapping the types in `ManuallyDrop` and then using `ManuallyDrop::drop` in the gc handler. This seems like something the API should handle for you, or at least something added to the documentation.

**Comment by GrayJack** [comment]
Yes, nice catch, I had a similar issue with it last week!

I'm investigating the possibilities to make that less error-prone.

**Comment by GrayJack** [comment]
@yrns 
I have found a way to solve this issue.

`JanetAbstract::new` always wraps the given value in a `ManuallyDrop` and what you get from the `get` family of functions now depends on the `IsJanetAbstract::Get` type. For non-`Drop` types, reinterpreting the type to `Self` is fine since `ManuallyDrop` is `repo(transparent)` and only disables the drop calls through compiler magic.

So, although it automatically wraps in `ManuallyDrop` on creation (`JanetAbstract::new`). It is the programmer's responsibility to implement `IsJanetAbstract` to get the correct type.

The downside of this approach is that the usage of turbo fish syntax will be required almost always when using the `get` functions

**Comment by yrns** [comment]
@GrayJack Sorry, I didn't understand this completely when I originally submitted the issue. Isn't this what you want?
```rust
// instead of: *unsafe { s.get_mut_unchecked() } = value;
unsafe { std::ptr::write(s.get_mut_unchecked(), value) };
```
[std::ptr::write](https://doc.rust-lang.org/std/ptr/fn.write.html) is semantically a move, and neither source or destination is dropped.

**Comment by GrayJack** [comment]
Looks like my solution for the `JanetAbstract::new` produced the same effects, but my solution doesn't have the same semantic guarantees after some more digging. I'll change that on the next commit
